### ISSUE TITLE
Verify the Gems in the Gemfile are needed and update all Gems

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/oawaiver#108]
Verify that the Gemfile has only the needed Gems.

When we upgraded to Jammy, Postgres 15 and Node 18.17 we noticed that Rubyracer and Node were being installed.  We also had to update webpacker to vite.

It is possible there are additional gems that are not needed.

If time permits see also if gems can be updated

**Comment by jrgriffiniii** [comment]
Once https://github.com/pulibrary/oawaiver/issues/116 is reviewed and merged, this should be resolved.
