### ISSUE TITLE
Database error in oawaiver?

### ISSUE THREAD

**Issue by kelynch** [pulibrary/oawaiver#121]
We had close to 300 `FATAL` errors from oawaiver over the last week with a not-very-descriptive message ([view here in DataDog](https://app.datadoghq.com/logs?query=host%3A%28lib-solr-prod3%20OR%20tigerdata-prod2%20OR%20tigerdata-prod1%20OR%20oawaiver-prod2%29%20-status%3A%28info%20OR%20ok%20OR%20error%20OR%20warn%29%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&saved-view-id=2137895&stream_sort=desc&view=spans&viz=stream&from_ts=1697635304958&to_ts=1698931304958&live=true)).

They seem to have stopped as of 4:00PM EST yesterday so no action may be required, but I wanted to raise this in case action is needed.

**Comment by jrgriffiniii** [comment]
I am very sorry, I was mistaken, the production host is currently utilizing `lib-solr-prod4`:

```bash
APP_SOLR_HOST=lib-solr-prod4.princeton.edu
APP_SOLR_PORT=8983
APP_SOLR_PATH=/solr/oawaiver-production
```

**Comment by jrgriffiniii** [comment]
Refining the dashboard to the following still does not lead me to any diagnosis:

https://app.datadoghq.com/logs?query=host%3A%28lib-solr-prod4%20OR%20oawaiver-prod2%20OR%20oawaiver-prod1%29%20-status%3A%28info%20OR%20ok%20OR%20error%20OR%20warn%29%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&saved-view-id=2137895&stream_sort=desc&view=spans&viz=stream&from_ts=1697635304958&to_ts=1698931304958&live=true

**Comment by kelynch** [comment]
Thanks for looking into this, James.  I think we can close this for now.

**Comment by kelynch** [comment]
It looks like it happened again about 30 times on 11/2/23, and so far twice on 11/3/23 (this morning at 8:43AM EST).
