### ISSUE TITLE
Where is the private key for oaworkflow.princeton.edu (and oaworkflow-dev.princeton.edu)

### ISSUE THREAD

**Issue by bess** [pulibrary/oawaiver#123]
Most of our servers are using the ACME automatic cert renewal, but oawaiver does not use it. 
Our (undocumented?) practice is to put the private key in princeton_ansible/keys, but there is not one there for oawaiver. 

- [ ] Has this been renewed for 2024? 
- [ ] Where is the key and can we put it somewhere expected?

**Comment by kayiwa** [comment]
heya @jrgriffiniii and apologies @bess we want the private keys for 

oaworkflow.princeton.edu and oaworkflow-dev.princeton.edu
