### ISSUE TITLE
Ensure that Coveralls code reporting is properly functioning for coveralls.io

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/oawaiver#153]
Currently the code coverage reporting for Coveralls is broken:

![image](https://github.com/pulibrary/oawaiver/assets/1443986/92d05137-8d18-42c1-b9f5-169dbc09d87a)

This blocks https://github.com/pulibrary/oawaiver/issues/135 from being resolved.

**Comment by jrgriffiniii** [comment]
Coveralls.io is now reporting for branches other than `main`:
![image](https://github.com/pulibrary/oawaiver/assets/1443986/066770e0-bc98-4b67-969e-a38464d3fff6)

**Comment by jrgriffiniii** [comment]
I am still struggling to understand exactly what triggered the initial build for the new branch, but does not for subsequent builds. I currently find the following for a newly-created branch:
<img width="1681" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87f4e1b85a82ceb66a48fe7d8c400b34fe6a5d85/image.png" alt="image.png" />

**Comment by leefaisonr** [comment]
Fixed.
