### ISSUE TITLE
use postgresql db

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/oawaiver#19]
Not sure if this is a distraction. We have more postgresql experience on the team. Might be worth our while to attempt a migration to postgresql "assuming it is straightforward".

**Comment by jrgriffiniii** [comment]
The commits for https://github.com/pulibrary/oawaiver/compare/issues-14-jrgriffiniii-cas...jrgriffiniii-fix-deployments and https://github.com/pulibrary/princeton_ansible/pull/2418 ensure that the Solr indexes are created for indexing using the `sunspot` Gem, as well as provide support for migrating the MySQL database tables to PostgreSQL.
