### ISSUE TITLE
RSpec tests inconsistently fail on CircleCI

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/oawaiver#196]
Please compare the following on CircleCI:
- https://app.circleci.com/pipelines/github/pulibrary/oawaiver/734/workflows/40b8ed93-4d43-4241-83f8-ba84ad4f22ad
- https://app.circleci.com/pipelines/github/pulibrary/oawaiver/734/workflows/6dc1065f-c480-4a06-874d-439746e02980

Acceptance Criteria:
- [ ] All test suites should pass consistently for local development environments
- [ ] All test suites should pass consistently for CircleCI jobs
- [ ] Add a retry gem if it is not obvious why the test is flaky.  Time box the investigation to a day.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/oawaiver/196?planning-poker) with Zenhub @bess @hectorcorrea @JaymeeH @leefaisonr
