### ISSUE TITLE
Security audit

### ISSUE THREAD

**Issue by bess** [pulibrary/oawaiver#3]
- [x] Is there any data we shouldn't expose? 
- [x] If not, move the code to a public repo pulibrary/oawaiver (this repo)

**Comment by jrgriffiniii** [comment]
There are definitely hard-coded server names within the README documentation which must be removed, but much of this looks to be relatively simple to clean and commit to a branch for this repository.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/oawaiver/compare/issues-3-jrgriffiniii-security?expand=1 tracks these changes, I will finish this and open a pull request (I apologize for creating the `main` branch, pushing first to `issues-3-jrgriffiniii-security` without creating a `main` automatically set `issues-3-jrgriffiniii-security` as the default branch).

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/oawaiver/pull/12 should have this resolved, but I also wanted to ensure that Dependabot alerts were enabled on https://github.com/pulibrary/oawaiver/settings/security_analysis before closing this.
